#!/bin/bash

# Ensure the necessary arguments were passed
[[ "$#" < 2 ]] && {
  echo "Must provide a tag name and repository"; exit 1;
}

# Prompt user to login
sudo docker login

# Build the tag
TAG_NAME="$1"
sudo docker build --no-cache -t "$TAG_NAME" .

# Get the tag ID from the name
TAG_ID=$(sudo docker images | awk -v tag=$TAG_NAME '$1==tag{print $3}')

# Ensure that the tag was found
[ -z "$TAG_ID" ] && {
  echo "Unable to find tag"; exit 2;
}

# Tag and push to repository
REPO="$2"
sudo docker tag $TAG_ID "$REPO":latest
sudo docker push "$2"
